{% set version = "0.3.1" %}

package:
  name: fastbencode
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/fastbencode/fastbencode-{{ version }}.tar.gz
  sha256: 5fe0cb7d1736891af61d2ade40ce948941d46e908b16f5383f55f127848da197

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
  host:
    - cython
    - pip
    - python
    - setuptools
  run:
    - python

test:
  commands:
    - pip check
  imports:
    - fastbencode
  requires:
    - pip
    - python

about:
  home: https://github.com/breezy-team/fastbencode
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Implementation of bencode with optional fast C extensions

extra:
  recipe-maintainers:
    - danielnachun
